language: node_js
node_js:
  - "18"

os:
  - linux
  - osx
  - windows

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn compile

notifications:
  email: false
